services:
  app:
    # image: guillesanz21/course.django.app
    build:
      context: .
      args:
        - DEV=true
    container_name: course.django.app
    hostname: app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/app
      - dev-static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: course.django.db
    hostname: db
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
  dev-static-data:
