---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub # Login to Docker Hub to pull the image
        uses: docker/login-action@v1 # Premade action to login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout  # Checkout the code from the repository (we need to do this to access the code (for testing and linting))
        uses: actions/checkout@v2 # Premade action to checkout the code from the repository

      - name: Test # Run the tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint  # Run the linter
        run: docker compose run --rm app sh -c "flake8"